name: Linting Testing Building
on:
  push:
    branches: [main]
  pull_request:
    branches: [dev]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Build production
        run: npm run build:prod
      - name: Lint TypeScript
        run: npm run lint:ts
      - name: Lint CSS
        run: npm run stylelint:scss
      - name: Run unit tests
        run: npm run test:unit
      # - name: Run UI tests
      #   run: npm run test:ui
      - name: Build Storybook
        run: npm run storybook:build
        - name: ScreenShot Tests
        run: npm run test:ui:ci
